-- ===========================================================================
-- transformation / 01 - HEADER_MAP reference table
--
-- The single place where structural interpretation of Qima's spreadsheet
-- lives. Ingestion and extraction stay dumb (see ingestion/docs/); everything
-- about what a column MEANS is data in this table, not code.
--
-- Grain: one row per (GENERATION, COLUMN_INDEX).
-- Seeded from transformation/reference_data/header_map/header_map_seed.csv,
-- which is generated by build_header_map.py and reviewed by hand.
--
-- Adding a new template generation is an INSERT here, not a code change. That
-- is the whole point - per the input data contract, an unrecognised column is
-- a convention-class issue to log, never a reason to reject a file.
-- ===========================================================================

use role "SF_APA_SANDBOX-ETL";
use warehouse SANDBOX_WH;
use schema SANDBOX_DB.HR_PAYROLL_QIMA;

create table if not exists HEADER_MAP (
    GENERATION          varchar        not null
        comment 'Template generation, <sheet year>-<column count>col, e.g. 2026-75col.',
    COLUMN_INDEX        number(38,0)   not null
        comment 'Zero-based position in the sheet row array.',
    COLUMN_LETTER       varchar
        comment 'Excel column reference, for talking to Qima about a specific column.',
    SHEET_YEAR          number(4,0)    not null,
    GENERATION_STATUS   varchar        not null default 'SUPPORTED'
        comment 'SUPPORTED = a real Qima submission template. SAMPLE = a test artefact that must never be treated as payroll. SharePoint has exactly three owner folders, so there are three real files; 2026-64col came from a sample workbook parked in the live BR02 folder.',

    GROUP_HEADER        varchar
        comment 'Row 0 merged band label, forward-filled across the columns it spans.',
    SOURCE_HEADER       varchar
        comment 'Row 1 header text, verbatim - embedded newlines and trailing spaces included.',

    COMPONENT_GROUP     varchar        not null
        comment 'SALARY | BONUS | COMMISSION | EXTERNAL | ADHOC per the data contract, plus EMPLOYEE and OTHER for non-payment columns.',
    COMPONENT_NAME      varchar        not null
        comment 'The specific scheme, e.g. YEAR_END, CCLAB, EID_FESTIVAL_FEB, MONTHLY_SALARY.',
    MEASURE_BASIS       varchar        not null
        comment 'PAYMENT | RATE | FEE per the contract, plus ELIGIBILITY, CURRENCY and ATTRIBUTE for the columns that qualify a payment rather than being one.',
    PERIOD_TYPE         varchar
        comment 'MONTH | QUARTER | FY. Null for eligibility, currency and attribute columns.',
    PERIOD_KEY          varchar
        comment 'YYYY-MM, YYYY-Qn, or YYYY. Null where PERIOD_TYPE is null.',

    CURRENCY_SCOPE      varchar        not null default 'LOCAL'
        comment 'LOCAL | USD | NA. The 2024/2025 generations carry a second copy of most amounts converted to USD at unknown FX rates. FX normalisation is out of scope per the contract, so USD columns load but must never be summed alongside LOCAL ones.',

    NEEDS_REVIEW        boolean        not null default false
        comment 'TRUE where the draft classifier could not decide. Load anyway, exclude from GOLD.',
    REVIEW_REASON       varchar,
    RESOLUTION_NOTE     varchar
        comment 'Set where a band/header conflict was resolved deliberately. Both known conflicts are defects in Qima template, documented in build_header_map.py.',

    CREATED_AT          timestamp_tz   not null default current_timestamp(),

    constraint PK_HEADER_MAP primary key (GENERATION, COLUMN_INDEX),
    constraint CHK_COMPONENT_GROUP check (COMPONENT_GROUP in
        ('SALARY','BONUS','COMMISSION','EXTERNAL','ADHOC','EMPLOYEE','OTHER','UNKNOWN')),
    constraint CHK_MEASURE_BASIS check (MEASURE_BASIS in
        ('PAYMENT','RATE','FEE','ELIGIBILITY','CURRENCY','ATTRIBUTE','UNKNOWN')),
    constraint CHK_PERIOD_TYPE check (PERIOD_TYPE is null or PERIOD_TYPE in ('MONTH','QUARTER','FY')),
    constraint CHK_CURRENCY_SCOPE check (CURRENCY_SCOPE in ('LOCAL','USD','NA')),
    constraint CHK_GENERATION_STATUS check (GENERATION_STATUS in ('SUPPORTED','SAMPLE'))
) comment = 'Header-to-meaning mapping, one row per column per template generation. Drives all transformation; new generations are inserted here rather than coded for.';

-- ---------------------------------------------------------------------------
-- Load the reviewed seed.
--
--   snow stage copy transformation/reference_data/header_map/header_map_seed.csv \
--        @%HEADER_MAP -c qima
--
-- then:
-- ---------------------------------------------------------------------------
create file format if not exists FF_HEADER_MAP_CSV
    type = 'CSV' skip_header = 1 field_optionally_enclosed_by = '"'
    empty_field_as_null = true trim_space = false
    comment = 'For loading header_map_seed.csv. TRIM_SPACE is off deliberately - some source headers carry a meaningful trailing space.';

-- copy into HEADER_MAP (
--     GENERATION, GENERATION_STATUS, SHEET_YEAR, COLUMN_INDEX, COLUMN_LETTER, GROUP_HEADER, SOURCE_HEADER,
--     COMPONENT_GROUP, COMPONENT_NAME, MEASURE_BASIS, PERIOD_TYPE, PERIOD_KEY,
--     CURRENCY_SCOPE, NEEDS_REVIEW, REVIEW_REASON, RESOLUTION_NOTE)
-- from @%HEADER_MAP/header_map_seed.csv
-- file_format = (format_name = FF_HEADER_MAP_CSV)
-- on_error = 'ABORT_STATEMENT';

-- ---------------------------------------------------------------------------
-- Generation lookup: resolves a sheet in FILE_LOAD to a HEADER_MAP generation.
-- Matching on (sheet name, column count) rather than a header hash is
-- deliberate - a single corrected typo in one header would change the hash and
-- orphan the file, whereas the column count is stable across such edits.
-- Sheets that match nothing here are convention-class, not rejections.
-- ---------------------------------------------------------------------------
create or replace view V_SHEET_GENERATION as
select f.LOAD_ID,
       f.FILE_NAME,
       f.IS_CURRENT,
       s.key                                            as SHEET_NAME,
       try_to_number(s.key)                             as SHEET_YEAR,
       array_size(s.value)                              as TOTAL_ROWS,
       array_size(s.value[1])                           as COLUMN_COUNT,
       s.key || '-' || array_size(s.value[1]) || 'col'  as GENERATION,
       hash(s.value[1]::string)                         as HEADER_HASH,
       exists (select 1 from HEADER_MAP m
               where m.GENERATION = s.key || '-' || array_size(s.value[1]) || 'col'
                 and m.GENERATION_STATUS = 'SUPPORTED')  as IS_MAPPED,
       exists (select 1 from HEADER_MAP m
               where m.GENERATION = s.key || '-' || array_size(s.value[1]) || 'col'
                 and m.GENERATION_STATUS = 'SAMPLE')     as IS_SAMPLE
from FILE_LOAD f,
     lateral flatten(input => f.RAW_CONTENT) s
where s.key rlike '^[0-9]{4}$';   -- year sheets only; "Instructions" is not data

show tables like 'HEADER_MAP' in schema SANDBOX_DB.HR_PAYROLL_QIMA;
