-- ===========================================================================
-- transformation / 01 - HEADER_MAP reference table
--
-- The single place where structural interpretation of Qima's spreadsheet
-- lives. Ingestion and extraction stay dumb (see ingestion/docs/); everything
-- about what a column MEANS is data in this table, not code.
--
-- Grain: one row per (GENERATION, COLUMN_INDEX).
-- Seeded from transformation/reference_data/header_map/header_map_seed.csv,
-- which is generated by build_header_map.py and reviewed by hand.
--
-- Adding a new template generation is an INSERT here, not a code change. That
-- is the whole point - per the input data contract, an unrecognised column is
-- a convention-class issue to log, never a reason to reject a file.
-- ===========================================================================

use role "SF_APA_SANDBOX-ETL";
use warehouse SANDBOX_WH;
use schema SANDBOX_DB.HR_PAYROLL_QIMA;

create table if not exists HEADER_MAP (
    GENERATION          varchar        not null
        comment 'Template generation, <sheet year>-<column count>col, e.g. 2026-75col.',
    COLUMN_INDEX        number(38,0)   not null
        comment 'Zero-based position in the sheet row array.',
    COLUMN_LETTER       varchar
        comment 'Excel column reference, for talking to Qima about a specific column.',
    SHEET_YEAR          number(4,0)    not null,
    GENERATION_STATUS   varchar        not null default 'SUPPORTED'
        comment 'SUPPORTED = a real Qima submission template. SAMPLE = a test artefact that must never be treated as payroll. SharePoint has exactly three owner folders, so there are three real files; 2026-64col came from a sample workbook parked in the live BR02 folder.',

    GROUP_HEADER        varchar
        comment 'Row 0 merged band label, forward-filled across the columns it spans.',
    SOURCE_HEADER       varchar
        comment 'Row 1 header text, verbatim - embedded newlines and trailing spaces included.',

    COMPONENT_GROUP     varchar        not null
        comment 'SALARY | BONUS | COMMISSION | EXTERNAL | ADHOC per the data contract, plus EMPLOYEE and OTHER for non-payment columns.',
    COMPONENT_NAME      varchar        not null
        comment 'The specific scheme, e.g. YEAR_END, CCLAB, EID_FESTIVAL_FEB, MONTHLY_SALARY.',
    MEASURE_BASIS       varchar        not null
        comment 'PAYMENT | RATE | FEE per the contract, plus ELIGIBILITY, CURRENCY and ATTRIBUTE for the columns that qualify a payment rather than being one, and LIMIT for the Max columns. Tess confirmed on 15 September that a Max amount is the ceiling finance budgets against, not what the employee is owed, so it is separated from RATE: summing every RATE would otherwise add contractual pay to budget ceilings.',
    CANONICAL_FIELD     varchar
        comment 'Which specific field this column is, where the loader needs it by name - EMPLOYEE_SAP_ID, SUBSIDIARY, JOIN_DATE, LEAVE_DATE, CONTRACT_CURRENCY and so on. COMPONENT_NAME says which scheme a column belongs to, not which field it is: all 88 employee columns are EMPLOYEE_ATTR. Position cannot be assumed either - the employee id is at index 0 in the 2026 generations and index 1 in 2024/2025, and the subsidiary is called Company Code in 2024.',
    PERIOD_TYPE         varchar
        comment 'MONTH | QUARTER | FY. Null for eligibility, currency and attribute columns.',
    PERIOD_KEY          varchar
        comment 'YYYY-MM, YYYY-Qn, or YYYY. Null where PERIOD_TYPE is null.',

    CURRENCY_SCOPE      varchar        not null default 'LOCAL'
        comment 'LOCAL | USD | NA. The 2024/2025 generations carry a second copy of most amounts converted to USD at unknown FX rates. FX normalisation is out of scope per the contract, so USD columns load but must never be summed alongside LOCAL ones.',

    NEEDS_REVIEW        boolean        not null default false
        comment 'TRUE where the draft classifier could not decide. Load anyway, exclude from GOLD.',
    REVIEW_REASON       varchar,
    RESOLUTION_NOTE     varchar
        comment 'Set where a band/header conflict was resolved deliberately. Both known conflicts are defects in Qima template, documented in build_header_map.py.',

    CREATED_AT          timestamp_tz   not null default current_timestamp(),

    constraint PK_HEADER_MAP primary key (GENERATION, COLUMN_INDEX),
    constraint CHK_COMPONENT_GROUP check (COMPONENT_GROUP in
        ('SALARY','BONUS','COMMISSION','EXTERNAL','ADHOC','EMPLOYEE','OTHER','UNKNOWN')),
    constraint CHK_MEASURE_BASIS check (MEASURE_BASIS in
        ('PAYMENT','RATE','LIMIT','FEE','ELIGIBILITY','CURRENCY','ATTRIBUTE','UNKNOWN')),
    constraint CHK_PERIOD_TYPE check (PERIOD_TYPE is null or PERIOD_TYPE in ('MONTH','QUARTER','FY')),
    constraint CHK_CURRENCY_SCOPE check (CURRENCY_SCOPE in ('LOCAL','USD','NA')),
    constraint CHK_GENERATION_STATUS check (GENERATION_STATUS in ('SUPPORTED','SAMPLE'))
) comment = 'Header-to-meaning mapping, one row per column per template generation. Drives all transformation; new generations are inserted here rather than coded for.';

-- ---------------------------------------------------------------------------
-- Load the reviewed seed.
--
--   snow stage copy transformation/reference_data/header_map/header_map_seed.csv \
--        @%HEADER_MAP -c qima
--
-- then:
-- ---------------------------------------------------------------------------
create file format if not exists FF_HEADER_MAP_CSV
    type = 'CSV' skip_header = 1 field_optionally_enclosed_by = '"'
    empty_field_as_null = true trim_space = false
    comment = 'For loading header_map_seed.csv. TRIM_SPACE is off deliberately - some source headers carry a meaningful trailing space.';

-- copy into HEADER_MAP (
--     GENERATION, GENERATION_STATUS, SHEET_YEAR, COLUMN_INDEX, COLUMN_LETTER, GROUP_HEADER, SOURCE_HEADER,
--     COMPONENT_GROUP, COMPONENT_NAME, MEASURE_BASIS, PERIOD_TYPE, PERIOD_KEY,
--     CURRENCY_SCOPE, NEEDS_REVIEW, REVIEW_REASON, RESOLUTION_NOTE)
-- from @%HEADER_MAP/header_map_seed.csv
-- file_format = (format_name = FF_HEADER_MAP_CSV)
-- on_error = 'ABORT_STATEMENT';

-- ---------------------------------------------------------------------------
-- COMPONENT_OVERRIDE - where one column means different things to different
-- subsidiaries.
--
-- HEADER_MAP answers "what is this column" per generation. That is enough
-- everywhere except one case Deepanjali confirmed with Qima's HR on 16
-- September: in 2025-96col, Bangladesh files the Eid festival bonus into the
-- 13th month and Christmas blocks. The band labels say so out loud - "13th
-- Month salary-Cebu/SBE MX bonus (paid in each Dec) BD Eid Festival Bonus
-- (Mar)" - so the same column is a 13th month for Cebu and Mexico and an Eid
-- bonus for Bangladesh.
--
-- Renaming the column in HEADER_MAP would relabel Cebu's and Mexico's 13th
-- month as Eid, which is why this is keyed on subsidiary rather than folded
-- into the generation. Today BD01 is the only subsidiary with values in those
-- blocks, but the template is shared, so the narrow key is the point.
--
-- Keyed on component rather than column index: a block is four or five columns
-- that all carry the same component, and all of them move together.
-- ---------------------------------------------------------------------------
create table if not exists COMPONENT_OVERRIDE (
    GENERATION          varchar        not null,
    COMPONENT_NAME_FROM varchar        not null comment 'The component HEADER_MAP resolves the column to.',
    SUBSIDIARY_CODE     varchar        not null comment 'PAYROLL_ROW.SUBSIDIARY_CODE this override applies to. Every other subsidiary keeps the HEADER_MAP name.',
    COMPONENT_NAME_TO   varchar        not null,
    NOTE                varchar        not null comment 'Who confirmed it and when. An override without a source is a guess.',
    CREATED_AT          timestamp_tz   not null default current_timestamp(),
    constraint PK_COMPONENT_OVERRIDE primary key (GENERATION, COMPONENT_NAME_FROM, SUBSIDIARY_CODE)
) comment = 'Per-subsidiary component renames, for columns a shared template uses for two different schemes.';

-- Seeded, not accumulated: this is reference data small enough to read in full,
-- and a rerun of this script must leave exactly these rows.
delete from COMPONENT_OVERRIDE;

insert into COMPONENT_OVERRIDE
    (GENERATION, COMPONENT_NAME_FROM, SUBSIDIARY_CODE, COMPONENT_NAME_TO, NOTE)
values
    ('2025-96col', 'THIRTEENTH_MONTH', 'BD01', 'EID_FESTIVAL_MAR',
     'Deepanjali Bhatt, 16 Sep 2026, confirmed with the respective HR: Bangladesh values in this block are the Eid festival bonus paid in March. The 2026 template gives Eid its own blocks.'),
    ('2025-96col', 'CHRISTMAS', 'BD01', 'EID_FESTIVAL_MAY',
     'Deepanjali Bhatt, 16 Sep 2026, confirmed with the respective HR: Bangladesh values in this block are the Eid festival bonus paid in May. The 2026 template gives Eid its own blocks.');

-- ---------------------------------------------------------------------------
-- Generation lookup: resolves a tab in FILE_LOAD to a HEADER_MAP generation.
-- Matching on (sheet name, column count) rather than a header hash is
-- deliberate - a single corrected typo in one header would change the hash and
-- orphan the file, whereas the column count is stable across such edits.
-- Sheets that match nothing here are convention-class, not rejections.
-- ---------------------------------------------------------------------------
create or replace view V_TAB_GENERATION as
select f.LOAD_ID,
       f.FILE_NAME,
       f.IS_CURRENT,
       s.key                                            as TAB_NAME,
       try_to_number(s.key)                             as TAB_YEAR,
       array_size(s.value)                              as TOTAL_ROWS,
       array_size(s.value[1])                           as COLUMN_COUNT,
       s.key || '-' || array_size(s.value[1]) || 'col'  as GENERATION,
       hash(s.value[1]::string)                         as HEADER_HASH,
       exists (select 1 from HEADER_MAP m
               where m.GENERATION = s.key || '-' || array_size(s.value[1]) || 'col'
                 and m.GENERATION_STATUS = 'SUPPORTED')  as IS_MAPPED,
       exists (select 1 from HEADER_MAP m
               where m.GENERATION = s.key || '-' || array_size(s.value[1]) || 'col'
                 and m.GENERATION_STATUS = 'SAMPLE')     as IS_SAMPLE
from FILE_LOAD f,
     lateral flatten(input => f.RAW_CONTENT) s
where s.key rlike '^[0-9]{4}$';   -- year sheets only; "Instructions" is not data

show tables like 'HEADER_MAP' in schema SANDBOX_DB.HR_PAYROLL_QIMA;
