
SELECT 
RUN_ID,
SHAREPOINT_ITEM_ID,
FILE_NAME,
IS_CURRENT,
INGEST_STATUS,
EXTRACT_STATUS,
RAW_CONTENT,
ERROR_MESSAGE

FROM FILE_LOAD;
WHERE SHAREPOINT_ITEM_ID = '01NLVSOQY67ML7PVUOXVHK6V4IUVHJLZZO';


SELECT LOAD_ID, FILE_NAME, EXTRACT_STATUS, 
       TYPEOF(RAW_CONTENT) as content_type,
       ARRAY_SIZE(OBJECT_KEYS(RAW_CONTENT)) as num_sheets,
       OBJECT_KEYS(RAW_CONTENT) as sheet_names
FROM SANDBOX_DB.HR_PAYROLL_QIMA.FILE_LOAD 
WHERE EXTRACT_STATUS = 'SUCCESS' AND IS_CURRENT = TRUE
ORDER BY INGESTED_AT DESC
LIMIT 5