USE DATABASE SANDBOX_DB;
USE SCHEMA HR_PAYROLL_QIMA;

CREATE OR REPLACE NETWORK RULE QIMA_GRAPH_NETWORK_RULE
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('login.microsoftonline.com:443', 'graph.microsoft.com:443');

CREATE OR REPLACE SECURITY INTEGRATION QIMA_GRAPH_OAUTH
  TYPE = API_AUTHENTICATION
  AUTH_TYPE = OAUTH2
  ENABLED = TRUE
  OAUTH_CLIENT_ID = '<CLIENT_ID>'
  OAUTH_CLIENT_SECRET = '<CLIENT_SECRET>'
  OAUTH_TOKEN_ENDPOINT = 'https://login.microsoftonline.com/77fc8d6c-15ec-4aea-9bd6-cf77b407a763/oauth2/v2.0/token'
  OAUTH_ALLOWED_SCOPES = ('https://graph.microsoft.com/.default');


CREATE OR REPLACE SECRET QIMA_GRAPH_SECRET
  TYPE = OAUTH2
  API_AUTHENTICATION = QIMA_GRAPH_OAUTH
  OAUTH_SCOPES = ('https://graph.microsoft.com/.default')
  COMMENT = 'OAuth2 token for SharePoint payroll reader (managed by Snowflake)';


CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION QIMA_GRAPH_EAI
  ALLOWED_NETWORK_RULES = (QIMA_GRAPH_NETWORK_RULE)
  ALLOWED_AUTHENTICATION_SECRETS = (QIMA_GRAPH_SECRET)
  ENABLED = TRUE;